# Generated by Django 5.2.5 on 2025-09-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employe',
            options={'permissions': [('can_view_all_employees', 'Peut voir tous les employés'), ('can_manage_employee', 'Peut gérer les employés')]},
        ),
        migrations.AlterModelOptions(
            name='presence',
            options={'permissions': [('can_manage_presence', 'Peut gérer les présences'), ('can_view_all_reports', 'Peut voir les rapports de présence')]},
        ),
        migrations.AlterModelOptions(
            name='rapport',
            options={'permissions': [('can_view_reports', 'Peut voir les rapports'), ('can_generate_reports', 'Peut générer des rapports'), ('can_view_all_reports', 'Peut voir les rapports de tous les employés')]},
        ),
    ]
