# Generated by Django 5.2.5 on 2025-09-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_employe_options_alter_presence_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employe',
            options={'permissions': [('can_manage_employee', 'Peut gérer les employés'), ('can_view_all_employees', 'Peut voir tous les employés')], 'verbose_name': 'Employé', 'verbose_name_plural': 'Employés'},
        ),
        migrations.AlterModelOptions(
            name='presence',
            options={'ordering': ['-date', '-created_at'], 'permissions': [('can_manage_presence', 'Peut gérer les présences'), ('can_view_all_reports', 'Peut voir tous les rapports')], 'verbose_name': 'Présence', 'verbose_name_plural': 'Présences'},
        ),
        migrations.AlterModelOptions(
            name='rapport',
            options={'ordering': ['-created_at'], 'permissions': [('can_generate_reports', 'Peut générer des rapports')], 'verbose_name': 'Rapport', 'verbose_name_plural': 'Rapports'},
        ),
        migrations.AlterField(
            model_name='employe',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employe',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='presence',
            name='heure_arrivee',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presence',
            name='heure_sortie',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presence',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presence',
            name='statut',
            field=models.CharField(choices=[('absent', 'Absent'), ('arrive', 'Arrivé'), ('parti', 'Parti')], default='absent', max_length=20),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='contenu',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='type',
            field=models.CharField(choices=[('mensuel', 'Mensuel'), ('hebdomadaire', 'Hebdomadaire'), ('annuel', 'Annuel'), ('personnalise', 'Personnalisé')], max_length=20),
        ),
    ]
