### 1️⃣ Inscription d'un nouvel utilisateur
POST http://127.0.0.1:8000/api/users/register/
Content-Type: application/json

{
  "username": "zidane",
  "email": "zidane@gmail.com",
  "password": "Azerty1234@",
  "role": "staff" 
}
###
POST http://127.0.0.1:8000/api/users/register/
Content-Type: application/json

{
  "username": "yacoubou",
  "email": "yacoubou@gmail.com",
  "password": "Azerty1234@",
  "role": "staff" 
}

###
POST http://127.0.0.1:8000/api/ma-presence/arrivee/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjQsImV4cCI6MTc1ODI3MTcyMSwiaWF0IjoxNzU3ODM5NzIxLCJ0eXBlIjoiYWNjZXNzIn0.tQVCsbz_hvTQxsORF7JXbDaJqcZvf56U2CvflYR5Cm0

###
POST http://127.0.0.1:8000/api/ma-presence/sortie/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjQsImV4cCI6MTc1ODI3MTcyMSwiaWF0IjoxNzU3ODM5NzIxLCJ0eXBlIjoiYWNjZXNzIn0.tQVCsbz_hvTQxsORF7JXbDaJqcZvf56U2CvflYR5Cm0


###
GET http://127.0.0.1:8000/api/users/list/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjQsImV4cCI6MTc1ODI3MTcyMSwiaWF0IjoxNzU3ODM5NzIxLCJ0eXBlIjoiYWNjZXNzIn0.tQVCsbz_hvTQxsORF7JXbDaJqcZvf56U2CvflYR5Cm0

###
GET http://127.0.0.1:8000/api/rapports/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjQsImV4cCI6MTc1ODI3MTcyMSwiaWF0IjoxNzU3ODM5NzIxLCJ0eXBlIjoiYWNjZXNzIn0.tQVCsbz_hvTQxsORF7JXbDaJqcZvf56U2CvflYR5Cm0

### 8️⃣ Ajouter un employé (endpoint protégé, RBAC)
POST http://127.0.0.1:8000/api/employes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjQsImV4cCI6MTc1ODI3MTcyMSwiaWF0IjoxNzU3ODM5NzIxLCJ0eXBlIjoiYWNjZXNzIn0.tQVCsbz_hvTQxsORF7JXbDaJqcZvf56U2CvflYR5Cm0
Content-Type: application/json

{
  "nom": "geno",
  "prenom": "houessou",
  "email": "geno@gmail.com",
  "poste": "Développeuse",
  "telephone": "+22997000000"
}

###
POST http://127.0.0.1:8000/api/employes/













###
POST http://127.0.0.1:8000/api/users/login/
Content-Type: application/json

{
  "identifier": "zidane",
  "password": "Azerty1234@"
}







###
POST http://127.0.0.1:8000/api/users/login/
Content-Type: application/json


{
  "identifier": "didacticiel",
  "password": "mongestion_presence23@"
}


### 2️⃣ Login pour récupérer Access + Refresh tokens
POST http://127.0.0.1:8000/api/users/login/
Content-Type: application/json

{
  "identifier": "johndoe",
  "password": "Mecurepassword123@"
}

###
GET http://127.0.0.1:8000/api/ma-presence/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImV4cCI6MTc1ODIxNTY0MiwiaWF0IjoxNzU3NzgzNjQyLCJ0eXBlIjoiYWNjZXNzIn0.EaF-w3Fo5bMjYcnOsX-aIYdrNfiTVRYGeT_YJAX0TSA

###
POST http://127.0.0.1:8000/api/ma-presence/arrivee/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImV4cCI6MTc1ODIxNTY0MiwiaWF0IjoxNzU3NzgzNjQyLCJ0eXBlIjoiYWNjZXNzIn0.EaF-w3Fo5bMjYcnOsX-aIYdrNfiTVRYGeT_YJAX0TSA

###
POST http://127.0.0.1:8000/api/ma-presence/sortie/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImV4cCI6MTc1ODIxNTY0MiwiaWF0IjoxNzU3NzgzNjQyLCJ0eXBlIjoiYWNjZXNzIn0.EaF-w3Fo5bMjYcnOsX-aIYdrNfiTVRYGeT_YJAX0TSA





### 5️⃣ Tester la liste des utilisateurs (admin only)
GET http://127.0.0.1:8000/api/users/list/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNzU4MjYzODIzLCJpYXQiOjE3NTc4MzE4MjMsInR5cGUiOiJhY2Nlc3MifQ.eRUTcndRGHF83beEBx9Ji7xeiOf4OFHw40kexPc2Xao


### 6️⃣ Déconnexion
POST http://127.0.0.1:8000/api/users/logout/

### 7️⃣ Accéder à la liste des employés (endpoint protégé)
GET http://127.0.0.1:8000/api/employes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNzU3MzQzMTM1LCJpYXQiOjE3NTczNDIyMzUsInR5cGUiOiJhY2Nlc3MifQ.4fH6oY_yfdPq8Ll7rk3zIaviSCEbdygaJBF4y1d5ZkI



### 8️⃣ Ajouter un employé (endpoint protégé, RBAC)
POST http://127.0.0.1:8000/api/employes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNzU3MzQzMTM1LCJpYXQiOjE3NTczNDIyMzUsInR5cGUiOiJhY2Nlc3MifQ.4fH6oY_yfdPq8Ll7rk3zIaviSCEbdygaJBF4y1d5ZkI
Content-Type: application/json

{
  "nom": "Diallo2",
  "prenom": "Moussa2",
  "email": "moussa2@gmail.com",
  "poste": "Développeur",
  "telephone": "+22997000002"
}






### 9️⃣ Inscription d'un autre utilisateur (role: admin)
POST http://127.0.0.1:8000/api/users/register/
Content-Type: application/json

{
  "username": "testadmin2",
  "email": "test2@example.com",
  "password": "Password123@",
  "role": "admin"
}
### 10️⃣ Login avec le nouvel utilisateur pour récupérer Access + Refresh tokens  
POST http://127.0.0.1:8000/api/users/login/
Content-Type: application/json

{
  "identifier": "Didacticiel",
  "password": "root"
}
### 11️⃣ Ajouter un employé en spécifiant un user existant (endpoint protégé, RBAC)
GET http://127.0.0.1:8000/api/employes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImV4cCI6MTc1ODE5Njc3NiwiaWF0IjoxNzU3NzY0Nzc2LCJ0eXBlIjoiYWNjZXNzIn0.dx5oThhoNyCTpnax2DsWE7BUrIW554mFxuDb_gGtdH8
Content-Type: application/json

{
  "nom": "Admin User",
  "poste": "Admin",
  "email": "admin@example.com"
}

###
POST http://127.0.0.1:8000/api/users/register/
Content-Type: application/json

{
  "username": "yacoubou",
  "email": "yacoubou@gmail.com",
  "password": "Azerty1234@",
  "role": "rh"
}






from django.contrib.auth.models import Group, User
u = User.objects.get(username="Diallo")
g = Group.objects.get(name="Staff")
u.groups.add(g)



from django.contrib.auth.models import Group
from django.contrib.auth import get_user_model

User = get_user_model()
u = User.objects.get(username="didacticiel")
g = Group.objects.get(name="Admin")
u.groups.add(g)
u.groups.all()  